bogle-bogle/thepet-backoffice

- src/views/heendycar/BranchHeendyCar.js
> feat(HeendyCar) : 흰디카 예약현황 관리자 버튼 추가

- src/views/heendycar/BranchHeendyCar.js
> fix(HeendyCar) : button 수정

- src/views/heendycar/BranchHeendyCar.js
> feat(HeendyCar) : 관리자 페이지에서 흰디카 일련번호 확인가능

- src/views/heendycar/BranchHeendyCar.js
> fix(HeendyCar) : 흰디카 반납관련 코드 수정

- .github/workflows/main.yml
> feat(backoffice): 배포

- public/index.html
> fix(title): 페이지 title 수정

- .github/workflows/main.yml
- public/index.html
> 페이지 title 수정

- src/views/heendycar/BranchHeendyCar.js
- src/views/member/Member.js
- src/views/productregister/curation/Curation.js
- src/views/productregister/general/General.js
- src/views/statistics/productstatistics/Productstatistics.js
> axios를 api.js 사용으로 변경

- .github/workflows/main.yml
> fix(server): server url 추가

- src/views/member/Member.js
> feat(member): delete nickname

- src/views/heendycar/BranchHeendyCar.js
> fix(Heendycar): 예약현황 정렬 수정

- src/views/productregister/curation/Curation.js
- src/views/productregister/general/General.js
> fix : upload

- src/_nav.js
- src/layout/DefaultLayout.js
> style: 스타일 수정

- src/views/member/Member.js
> fix(member): 버튼 text 수정

- src/_nav.js
- src/views/member/Member.js
- src/views/member/custom-member.css
- src/views/productregister/curation/Curation.style.js
> fix(nav): nav 순서 수정

- src/api.js
- src/views/eventlog/EventLog.js
- src/views/eventlog/ProductCartRate.js
- src/views/eventlog/SuggestionLog.js
- src/views/heendycar/BranchHeendyCar.js
- src/views/member/Member.js
- src/views/product/Product.js
- src/views/productregister/curation/Curation.js
- src/views/productregister/general/General.js
- src/views/statistics/productstatistics/Productstatistics.js
> fix(상품 등록): 이미지 프리뷰

- src/views/member/Member.js
- src/views/statistics/productstatistics/Productstatistics.js
> fix(backoffice): 백오피스 스타일 및 member 날짜 수정

- src/views/member/Member.js
> fix(member): 1000의 자리 , 추가

- src/views/member/Member.js
- src/views/statistics/productstatistics/Productstatistics.js
> 1000의 자리 , 추가

- src/views/member/Member.js
> fix(member): 테이블 순서 수정

- src/views/statistics/productstatistics/Productstatistics.js
> fix(매출): 스타일 변경
